name: pop

on:
  workflow_dispatch:

jobs:
  generate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull latest changes with rebase
        run: |
          git pull https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/malka1-cic/pop.git main --rebase

      - name: Generate commits
        run: |
          touch activity.txt
          for i in {1..60}; do
            echo "Commit $i" >> activity.txt
            git config --global user.name "malka1-cic"
            git config --global user.email "malls-01-saga@icloud.com"
            git add .
            git commit --date="$(date -d "-$i days")" -m "Update activity"
          done
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/malka1-cic/pop.git main
