name: pop

on:
  workflow_dispatch:

jobs:
  generate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Gg
        run: |
          touch activity.txt
          for i in {1..60}; do
            echo "Commit $i" >> activity.txt
            git config --global user.name "Your Name"
            git config --global user.email "your-email@example.com"
            git add .
            git commit --date="$(date -d "-$i days")" -m "Update activity"
          done
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/malka1-cic/pop.git main
